### ISSUE TITLE
Bug with the Seconds

### ISSUE THREAD

**Issue by official-SirLester** [RolandDaum/Digital-Analog---Clock#1]
There is a bug where some seconds are skipped.

Seconds two and 8 in particular are often skipped and simply not displayed at all. 
System:
Win11
Surface Pro 8 Model 1983 i5
Version 61.23

Browser i used:
Google Chrome
Latest Version from 2023 September

**Comment by RolandDaum** [comment]
I can not reproduce the named issue. Therefore it doesn't really exist. It might be just a lag of performance in the browser, cause of the continues animation.
